name: Build & Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Test
    runs-on: windows
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore
        run: dotnet restore CheapFurniturePlanner.sln

      - name: Build
        run: dotnet build CheapFurniturePlanner.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test CheapFurniturePlanner.sln --no-build --configuration Release --verbosity normal
